" Name:         Test 66
" Author:       y
" Maintainer:   y
" License:      Vim License (see `:help license`)
" Last Updated: Wed Jun  5 10:00:41 2019

" Generated by Colortemplate v2.0.0b2

set background=light

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'test66'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2

if (has('termguicolors') && &termguicolors) || has('gui_running')
  hi Normal guifg=#000000 guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  if ok
  endif
  if wrong
  endif
  unlet s:t_Co
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=16 ctermbg=16 cterm=NONE
  if ok
  endif
  if wrong
    unlet s:t_Co
    finish
  endif

  " Background:light
  " Color:black #000000 16 Black
  " Normal black black
  " Variant:256
  " Variant: gui
  " Variant: 256 gui
  " Variant: gui
